import { z } from 'zod';

const PathsSchema = z.object({
  auth: z.object({
    signIn: z.string().min(1),
    signUp: z.string().min(1),
    verifyMfa: z.string().min(1),
    callback: z.string().min(1),
    postLogin: z.string().min(1),
    passwordReset: z.string().min(1),
    passwordUpdate: z.string().min(1),
  }),
  app: z.object({
    home: z.string().min(1),
    onboarding: z.string().min(1),
    crm: z.string().min(1),
    students: z.string().min(1),
    classes: z.string().min(1),
    finance: z.string().min(1),
    attendance: z.string().min(1),
    calendar: z.string().min(1),
    settingsSchool: z.string().min(1),
    settingsCampuses: z.string().min(1),
    settingsSubscription: z.string().min(1),
    crmLead: z.string().min(1),
    studentDetail: z.string().min(1),
    studentContracts: z.string().min(1),
    classDetail: z.string().min(1),
    financeInvoice: z.string().min(1),
    staff: z.string().min(1),
    staffDetail: z.string().min(1),
    staffSetup: z.string().min(1),
    staffPermissions: z.string().min(1),
    staffAttendance: z.string().min(1),
    staffLeave: z.string().min(1),
    staffReports: z.string().min(1),
    dailyReports: z.string().min(1),
    menu: z.string().min(1),
    menuDetail: z.string().min(1),
    inventory: z.string().min(1),
    ai: z.string().min(1),
    health: z.string().min(1),
    messages: z.string().min(1),
    suspended: z.string().min(1),
    account: z.string().min(1),
  }),
  platform: z.object({
    home: z.string().min(1),
    schools: z.string().min(1),
    schoolDetail: z.string().min(1),
    packages: z.string().min(1),
    admins: z.string().min(1),
    auditLogs: z.string().min(1),
    account: z.string().min(1),
  }),
  parent: z.object({
    home: z.string().min(1),
    child: z.string().min(1),
    account: z.string().min(1),
    calendar: z.string().min(1),
    messages: z.string().min(1),
  }),
});

const pathsConfig = PathsSchema.parse({
  auth: {
    signIn: '/auth/sign-in',
    signUp: '/auth/sign-up',
    verifyMfa: '/auth/verify',
    callback: '/auth/callback',
    postLogin: '/auth/post-login',
    passwordReset: '/auth/password-reset',
    passwordUpdate: '/update-password',
  },
  app: {
    home: '/app',
    onboarding: '/app/onboarding',
    crm: '/app/crm',
    students: '/app/students',
    classes: '/app/classes',
    finance: '/app/finance',
    attendance: '/app/attendance',
    calendar: '/app/calendar',
    settingsSchool: '/app/settings/school',
    settingsCampuses: '/app/settings/campuses',
    settingsSubscription: '/app/settings/subscription',
    crmLead: '/app/crm/leads',
    studentDetail: '/app/students',
    studentContracts: '/app/student-contracts',
    classDetail: '/app/classes',
    financeInvoice: '/app/finance/invoices',
    staff: '/app/staff',
    staffDetail: '/app/staff',
    staffSetup: '/app/staff/setup',
    staffPermissions: '/app/staff/permissions',
    staffAttendance: '/app/staff/attendance',
    staffLeave: '/app/staff/leave',
    staffReports: '/app/staff/reports',
    dailyReports: '/app/daily-reports',
    menu: '/app/menu',
    menuDetail: '/app/menu',
    inventory: '/app/inventory',
    ai: '/app/ai',
    health: '/app/health',
    messages: '/app/messages',
    suspended: '/app/suspended',
    account: '/app/account',
  },
  platform: {
    home: '/platform',
    schools: '/platform/schools',
    schoolDetail: '/platform/schools',
    packages: '/platform/packages',
    admins: '/platform/admins',
    auditLogs: '/platform/audit-logs',
    account: '/platform/account',
  },
  parent: {
    home: '/parent',
    child: '/parent/children',
    account: '/parent/account',
    calendar: '/parent/calendar',
    messages: '/parent/messages',
  },
} satisfies z.infer<typeof PathsSchema>);

export default pathsConfig;
