export const KINDER_ERROR_CODES = {
  SCHOOL_NOT_FOUND: 'SCHOOL_NOT_FOUND',
  SCHOOL_ACCESS_DENIED: 'SCHOOL_ACCESS_DENIED',
  SCHOOL_SLUG_TAKEN: 'SCHOOL_SLUG_TAKEN',
  NO_ACTIVE_SCHOOL: 'NO_ACTIVE_SCHOOL',
  PACKAGE_NOT_FOUND: 'PACKAGE_NOT_FOUND',
  PACKAGE_NOT_AVAILABLE: 'PACKAGE_NOT_AVAILABLE',
  CAMPUS_NOT_FOUND: 'CAMPUS_NOT_FOUND',
  CAMPUS_LIMIT_REACHED: 'CAMPUS_LIMIT_REACHED',
  STUDENT_LIMIT_REACHED: 'STUDENT_LIMIT_REACHED',
  FEATURE_NOT_AVAILABLE: 'FEATURE_NOT_AVAILABLE',
  LEAD_NOT_FOUND: 'LEAD_NOT_FOUND',
  STUDENT_NOT_FOUND: 'STUDENT_NOT_FOUND',
  CLASS_NOT_FOUND: 'CLASS_NOT_FOUND',
  CLASS_CAPACITY_REACHED: 'CLASS_CAPACITY_REACHED',
  INVOICE_NOT_FOUND: 'INVOICE_NOT_FOUND',
  STAFF_NOT_FOUND: 'STAFF_NOT_FOUND',
  PARENT_ACCESS_DENIED: 'PARENT_ACCESS_DENIED',
  PARENT_ACCOUNT_NOT_FOUND: 'PARENT_ACCOUNT_NOT_FOUND',
  ACCOUNT_PROVISION_FAILED: 'ACCOUNT_PROVISION_FAILED',
  CREDENTIALS_EMAIL_FAILED: 'CREDENTIALS_EMAIL_FAILED',
  PLATFORM_ACCESS_DENIED: 'PLATFORM_ACCESS_DENIED',
  SCHOOL_SUSPENDED: 'SCHOOL_SUSPENDED',
} as const;

export type KinderErrorCode =
  (typeof KINDER_ERROR_CODES)[keyof typeof KINDER_ERROR_CODES];

export class KinderError extends Error {
  constructor(
    public readonly code: KinderErrorCode,
    message: string,
  ) {
    super(message);
    this.name = 'KinderError';
  }
}
